name: Build APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 11
        
    - name: Build Project
      run: ./gradlew assemble
      
      
    - name: React Native Android Build APK
      uses: realabbas/Github-Actions-React-Native@v1.1.2
