name: Build APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.3.3
    
    - name: Set up JDK
      uses: actions/setup-java@v1.4.3
      with:
        java-version: 11
        
    - name: Build all artifacts
      uses: eskatos/gradle-command-action@v1.3.3
      with:
        gradle-version: current
        wrapper-cache-enabled: true
        dependencies-cache-enabled: true
        configuration-cache-enabled: true
        arguments: assembleRelease

      
    - name: Upload Artifact 
      uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: path/to/artifact/

 
